// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Multi-platform [FirebaseOptions] for DIU Events.
///
/// Generated from [android/app/google-services.json].
/// For iOS/macOS, run: `flutterfire configure` to add platform-specific configs.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported by this Firebase project.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android config from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGd11WGuEgf2KcJl7VjKg-bekG8JeuK9g',
    appId: '1:618114582605:android:a1e1d1916d395587ba7404',
    messagingSenderId: '618114582605',
    projectId: 'diuevents-3ecd4',
    storageBucket: 'diuevents-3ecd4.firebasestorage.app',
  );

  // iOS config — placeholder. Replace with values from GoogleService-Info.plist
  // after running: flutterfire configure
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd11WGuEgf2KcJl7VjKg-bekG8JeuK9g',
    appId: '1:618114582605:ios:a1e1d1916d395587ba7404',
    messagingSenderId: '618114582605',
    projectId: 'diuevents-3ecd4',
    storageBucket: 'diuevents-3ecd4.firebasestorage.app',
    iosBundleId: 'com.example.diuEvents',
  );

  // macOS config — shares the same appId base as iOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGd11WGuEgf2KcJl7VjKg-bekG8JeuK9g',
    appId: '1:618114582605:ios:a1e1d1916d395587ba7404',
    messagingSenderId: '618114582605',
    projectId: 'diuevents-3ecd4',
    storageBucket: 'diuevents-3ecd4.firebasestorage.app',
  );

  // Web config — uses same API key as Android
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGd11WGuEgf2KcJl7VjKg-bekG8JeuK9g',
    appId: '1:618114582605:android:a1e1d1916d395587ba7404',
    messagingSenderId: '618114582605',
    projectId: 'diuevents-3ecd4',
    storageBucket: 'diuevents-3ecd4.firebasestorage.app',
    authDomain: 'diuevents-3ecd4.firebaseapp.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  // Windows config — placeholder
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGd11WGuEgf2KcJl7VjKg-bekG8JeuK9g',
    appId: '1:618114582605:android:a1e1d1916d395587ba7404',
    messagingSenderId: '618114582605',
    projectId: 'diuevents-3ecd4',
    storageBucket: 'diuevents-3ecd4.firebasestorage.app',
  );
}
